    version: '3'
    
    services:
        ithappens:
            build: .
            ports:
                    - "8080:80"
            volumes:
                    # - ./:/media/luiz/DADOS/projetos/pessoal/ItHappens/storage/logs
                    - ./:/usr/share/nginx
            networks:
                - app-network
        
        mysql-app:
            image: mysql:5.7.22
            ports:
                    - "3306:3306"
            volumes:
                    # - ./:/media/luiz/DADOS/projetos/pessoal/ItHappens/storage/logs
                    - .docker/dbdata:/var/lib/mysql
                    
            environment: 
                MYSQL_DATABASE: laravel
                MYSQL_ROOT_PASSWORD: laravel

            networks:
                    - app-network

    networks:
        app-network:
            driver: bridge